# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: upb2025
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-image-app

package:
  exclude:
    - config.json
    - package.json
    - package-lock.json
    - README.md
    - .gitignore      
    - .serverless/**
    - node_modules/**
    - nodejs/**
    - layer_content.zip

provider:
  name: aws
  region: ${file(config.json):AWS_REGION}
  runtime: nodejs20.x
  environment:
    BUCKET_NAME: ${file(config.json):S3_IMAGE_BUCKET}
    TABLE_NAME: ${file(config.json):DYNAMODB_TABLE_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - rekognition:DetectLabels
      Resource:
        - arn:aws:s3:::${file(config.json):S3_IMAGE_BUCKET}/*
functions:
  danielGetSignedUrl:
    handler: handler.getSignedUrl
    events:
      - http:
          path: sign-url
          method: get
          cors: true

  danielProcessImage:
    handler: recognize.processImage
    layers:
      - { Ref: DanielDependenciesLambdaLayer }
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:Put
          existing: true


layers:
  danielDependencies:
    name: 'daniel-serverless-dependencies'
    compatibleRuntimes:
      - "nodejs20.x"
    package:
      artifact: layer_content.zip

resources:
 Resources:
   UploadBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${self:provider.environment.BUCKET_NAME}
   ImageTagsTable:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: ${self:provider.environment.TABLE_NAME}
       AttributeDefinitions:
         - AttributeName: image
           AttributeType: S
       KeySchema:
         - AttributeName: image
           KeyType: HASH
       BillingMode: PAY_PER_REQUEST